---
apiVersion: batch/v1
kind: Job
metadata:
  name: contour-certgen-v1.19.1
  namespace: projectcontour
spec:
  template:
    spec:
      containers:
      - name: contour
        image: projectcontour/contour:v1.19.1
        imagePullPolicy: IfNotPresent
