kind: JoinConfiguration
apiVersion: kubeadm.k8s.io/v1beta2
metadata:
  name: kubeadm-join-configuration
controlPlane:
  certificateKey: $CERT_KEY
  localAPIEndpoint:
    advertiseAddress: $PRIVATE_ADDRESS
