---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
metadata:
  name: kubeadm-init-configuration
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: $BOOTSTRAP_TOKEN
  ttl: $BOOTSTRAP_TOKEN_TTL
  usages:
  - signing
  - authentication
localAPIEndpoint:
  advertiseAddress: $PRIVATE_ADDRESS
nodeRegistration:
  taints: [] # prevent the default master taint
  name: $HOSTNAME
  kubeletExtraArgs:
    node-labels: "kurl.sh/cluster=true,$NODE_LABELS"
    hostname-override: $HOSTNAME
    node-ip: $PRIVATE_ADDRESS
